CREATE TABLE [dbo].[Authors]
(
	[Id] INT IDENTITY (1, 1) NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[DateCreatedAt] DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET() NOT NULL,
	[DateUpdatedAt] DATETIMEOFFSET,
	CONSTRAINT [PK_Authors] PRIMARY KEY CLUSTERED ([Id] ASC)
)
