CREATE TABLE [dbo].[Books]
(
	[Id] INT IDENTITY (1, 1) NOT NULL,
	[Title] NVARCHAR(255) NOT NULL,
	[ISBN] CHAR(13) NOT NULL,
	[YearPublished] SMALLINT NOT NULL,
	[PublisherId] INT NOT NULL,
	[DateCreatedAt] DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET() NOT NULL,
	[DateUpdatedAt] DATETIMEOFFSET NULL,
	CONSTRAINT [PK_Books] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_Books_Publishers] FOREIGN KEY ([PublisherId]) REFERENCES [dbo].[Publishers] ([Id])
)
