CREATE TABLE [dbo].[LibraryBranches]
(
	[Code] CHAR(2) NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT 1,
	[DateCreatedAt] DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
	[DateUpdatedAt] DATETIMEOFFSET,

	CONSTRAINT [PK_LibraryBranches] PRIMARY KEY CLUSTERED ([Code] ASC),
)
